### ISSUE TITLE
name 'c' is not defined in CADA/src/CADA/prioritizing.py

### ISSUE THREAD

**Issue by kyauy** [Chengyao-Peng/CADA#1]
Hi !

Thanks for providing CADA as a standalone tool.
I installed it through these commands as says in README
```
$ git clone https://github.com/Chengyao-Peng/CADA.git
$ cd CADA
$ pip install -e . 
```

Then I try to run CADA with this command but it failed

```
CADA --out_dir cada_result --hpo_terms HP:0000573,HP:0001102,HP:0003115,HP:0001681,HP:0008067,HP:0004417 --weighted False --topn 10
```

The error message
```
Traceback (most recent call last):
  File "/home/kevin/anaconda3/bin/CADA", line 11, in <module>
    load_entry_point('CADA', 'console_scripts', 'CADA')()
  File "/home/kevin/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/kevin/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/kevin/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kevin/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/kevin/dev_gre/phenogen/CADA/src/CADA/cli.py", line 38, in main
    prioritizing(hpo_terms, model_path, graph_path, out_dir, topn)
  File "/home/kevin/dev_gre/phenogen/CADA/src/CADA/prioritizing.py", line 46, in prioritizing
    gene_id_name_dict = c
NameError: name 'c' is not defined
```

Do you know where it come from ?

Thanks!
Kevin

**Comment by Chengyao-Peng** [comment]
I fixed the bug there. Could you try clone the repository and run the code again?
